name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Checkout Common.Diagnostics
        uses: actions/checkout@v4
        with:
          repository: fitzroywright/Common.Diagnostics
          path: Common.Diagnostics
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.0.x'
      - name: Restore
        run: dotnet restore Common.Security.slnx
      - name: Build
        run: dotnet build Common.Security.slnx -c Release --no-restore
      - name: Test
        run: dotnet test Common.Security.slnx -c Release --no-build
